import { City, POI } from './types';

export const cities: City[] = [
  {
    id: 'palermo',
    name: 'Palermo',
    region: 'Sicily',
    description: 'A city where Arab, Norman, and Baroque collide in sun-drenched chaos. Markets overflow with swordfish and wild fennel, while churches hide mosaics that shimmer like fever dreams.',
    imageUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800',
    highlights: ['Mercato di Ballarò', 'Teatro Massimo', 'Street Food', 'Norman Palace'],
  },
  {
    id: 'ortigia',
    name: 'Ortigia',
    region: 'Sicily',
    description: 'An island of honey-colored stone where narrow streets open suddenly to the blinding blue of the Ionian Sea. Every corner holds a baroque surprise, every piazza a fountain.',
    imageUrl: 'https://images.unsplash.com/photo-1567438574169-1f4e40d3f0ee?w=800',
    highlights: ['Duomo Square', 'Arethusa Fountain', 'Fresh Seafood', 'Ancient Greek Ruins'],
  },
  {
    id: 'aci-castello',
    name: 'Aci Castello',
    region: 'Sicily',
    description: 'A volcanic fortress town where black lava rocks meet impossibly clear water. The Norman castle stands sentinel over fishing boats painted every color imaginable.',
    imageUrl: 'https://images.unsplash.com/photo-1548963670-aaaa8f73a5e9?w=800',
    highlights: ['Norman Castle', 'Lava Rock Beaches', 'Fresh Fish', 'Mt. Etna Views'],
  },
  {
    id: 'mazara-del-vallo',
    name: 'Mazara del Vallo',
    region: 'Sicily',
    description: 'Where Africa whispers across the strait. The largest fishing fleet in Italy returns each dawn with prawns so sweet they taste of the sea itself. The Kasbah quarter remembers its Moorish past.',
    imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800',
    highlights: ['Dancing Satyr', 'Tunisian Quarter', 'Red Prawns', 'Cathedral Square'],
  },
  {
    id: 'marzamemi',
    name: 'Marzamemi',
    region: 'Sicily',
    description: 'A fishing village that time forgot, built around an ancient tonnara. Piazza Regina Margherita is barely bigger than a living room, but holds more life than cities ten times its size.',
    imageUrl: 'https://images.unsplash.com/photo-1558473399-baa2cd6d4662?w=800',
    highlights: ['Tonnara', 'Tiny Piazza', 'Fresh Tuna', 'Baroque Church'],
  },
  {
    id: 'giardini-naxos',
    name: 'Giardini Naxos',
    region: 'Sicily',
    description: 'The first Greek colony in Sicily, now a crescent of beach where the ancients first set foot. Taormina glitters on the cliff above, but down here the living is sweeter, simpler, cheaper.',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    highlights: ['Ancient Greek Site', 'Sandy Beaches', 'Seafood', 'Mt. Etna & Sea Views'],
  },
];

export const pois: POI[] = [
  // Palermo
  {
    id: 'ballar',
    name: 'Mercato di Ballarò',
    city: 'palermo',
    type: 'attraction',
    description: 'Ancient street market in the heart of Palermo\'s historic center',
    detailedDescription: 'The vendors call out in dialect so thick you could spread it on bread. Swordfish heads the size of small children glisten on ice. Blood oranges are stacked in pyramids that would make a pharaoh jealous. This is not a market for tourists—this is where Palermo feeds itself, and you are simply lucky enough to witness it. Grab a panino con panelle from the fry cart, squeeze into the crowd, and let the chaos wash over you like a warm Mediterranean wave.',
    address: 'Ballarò, Palermo, PA',
    coordinates: { lat: 38.1107, lng: 13.3562 },
    priceRange: '$',
    timing: 'Morning (7am-2pm)',
    tags: ['market', 'street food', 'authentic', 'morning'],
  },
  {
    id: 'antica-focacceria',
    name: 'Antica Focacceria San Francesco',
    city: 'palermo',
    type: 'restaurant',
    description: 'Historic trattoria serving traditional Palermo street food since 1834',
    detailedDescription: 'Since 1834, this place has been frying things that shouldn\'t work but absolutely do. The pani câ meusa—spleen sandwich—sounds like a dare, but one bite and you understand why it\'s survived nearly two centuries. The focaccia is blistered and perfect, the panelle are crisp as autumn leaves, and the arancine are molten golden orbs of joy. Sit at the worn wooden tables and eat with your hands. This is not fine dining—this is pure, unapologetic Palermo, and it\'s glorious.',
    address: 'Via A. Paternostro, 58, 90133 Palermo PA',
    coordinates: { lat: 38.1156, lng: 13.3615 },
    priceRange: '$',
    timing: 'Lunch & Dinner',
    tags: ['street food', 'historic', 'traditional', 'arancini'],
  },
  
  // Ortigia
  {
    id: 'duomo-ortigia',
    name: 'Duomo di Siracusa',
    city: 'ortigia',
    type: 'attraction',
    description: 'Baroque cathedral built into an ancient Greek temple',
    detailedDescription: 'Walk close to the side wall and you\'ll see them—the columns of the Temple of Athena, built 2,500 years ago, now embedded in a baroque cathedral. The Christians didn\'t destroy the pagan temple; they simply wrapped it in their own. Stand in the piazza as afternoon light hits the honey-colored facade, and you\'re standing in the same spot where Greek soldiers, Roman centurions, Arab traders, and Norman knights all stood before you. The continuity is staggering. The cappuccino at the cafe across the piazza isn\'t bad either.',
    address: 'Piazza Duomo, 96100 Siracusa SR',
    coordinates: { lat: 37.0595, lng: 15.2934 },
    priceRange: 'Free',
    timing: 'Morning & Afternoon',
    tags: ['ancient', 'baroque', 'historical', 'architecture'],
  },
  {
    id: 'caseificio-borderi',
    name: 'Caseificio Borderi',
    city: 'ortigia',
    type: 'shop',
    description: 'Legendary dairy shop making fresh ricotta daily',
    detailedDescription: 'Arrive before 11am or prepare for disappointment—they sell out. The ricotta here is so fresh it\'s still warm, so creamy it borders on obscene. This isn\'t the grainy, sad ricotta you know from supermarkets back home. This is clouds you can eat. Get it plain in a container, or in a pillowy brioche bun with a drizzle of local honey. Stand at the counter, eat it immediately, and try not to moan with pleasure. You will fail at that last part.',
    address: 'Via Emmanuele De Benedictis, 6, 96100 Siracusa SR',
    coordinates: { lat: 37.0619, lng: 15.2929 },
    priceRange: '$',
    timing: 'Morning (8am-1pm, often sells out)',
    tags: ['ricotta', 'dairy', 'breakfast', 'must-try'],
  },
  
  // Aci Castello
  {
    id: 'castello-normanno',
    name: 'Castello Normanno',
    city: 'aci-castello',
    type: 'attraction',
    description: 'Norman castle built on volcanic rock overlooking the sea',
    detailedDescription: 'The Norman castle perches on a black lava outcrop like a barnacle on a whale. Built nearly a thousand years ago, it has survived earthquakes, eruptions, and invasions. Climb to the top and the view is preposterous—Mount Etna smoking to the north, the Ionian Sea glittering to the east, fishing boats bobbing in the harbor below. The castle itself is modest, almost humble, but the setting is pure drama. Go at sunset and watch the sky turn the same orange as the Aperol in your spritz.',
    address: 'Piazza Castello, 95021 Aci Castello CT',
    coordinates: { lat: 37.5542, lng: 15.1470 },
    priceRange: '$',
    timing: 'Morning & Afternoon',
    tags: ['castle', 'norman', 'views', 'historical'],
  },
  {
    id: 'trattoria-del-castello',
    name: 'Trattoria del Castello',
    city: 'aci-castello',
    type: 'restaurant',
    description: 'Family-run trattoria with terrace overlooking the castle',
    detailedDescription: 'The pasta alle vongole arrives steaming, garlicky, the clams so fresh they taste of the sea that\'s crashing just meters away. This is a family place—three generations work the dining room and kitchen—and everything is done the way nonna taught them. The swordfish involtini are rolled thin as paper and stuffed with breadcrumbs, pine nuts, and currants. The house wine is from Etna\'s slopes, volcanic and slightly wild. Sit on the terrace, watch the sunset paint the castle gold, and understand why people never leave Sicily.',
    address: 'Via Vampolieri, 13, 95021 Aci Castello CT',
    coordinates: { lat: 37.5551, lng: 15.1463 },
    priceRange: '$$',
    timing: 'Lunch & Dinner',
    tags: ['seafood', 'family-run', 'terrace', 'local'],
  },
  
  // Mazara del Vallo
  {
    id: 'satiro-danzante',
    name: 'Museo del Satiro Danzante',
    city: 'mazara-del-vallo',
    type: 'attraction',
    description: 'Museum housing the famous Dancing Satyr bronze statue',
    detailedDescription: 'The Dancing Satyr was pulled from the sea in 1998, tangled in fishing nets. A Greek bronze from 2,300 years ago, preserved perfectly in the Mediterranean\'s embrace. He\'s caught mid-dance, one leg raised, arms outstretched, face lit with Dionysian joy. To stand before him is to stand before something that should not have survived—but did. The museum is small, focused, and the star is this one bronze that makes you believe in both art and miracles.',
    address: 'Piazza Plebiscito, 91026 Mazara del Vallo TP',
    coordinates: { lat: 37.6541, lng: 12.5900 },
    priceRange: '$',
    timing: 'Morning & Afternoon',
    tags: ['museum', 'ancient', 'art', 'bronze'],
  },
  {
    id: 'la-bettola',
    name: 'La Bettola',
    city: 'mazara-del-vallo',
    type: 'restaurant',
    description: 'Renowned for the best gamberi rossi (red prawns) in Sicily',
    detailedDescription: 'The gamberi rossi di Mazara are legendary—sweet, almost buttery, with flesh that practically melts on your tongue. La Bettola serves them simply: sautéed with olive oil, garlic, and a whisper of white wine. That\'s it. That\'s all they need. The prawns arrive still sizzling, heads on, and you work your way through them with your fingers, sucking the coral from the heads because to leave it would be a sin. This is not polite food. This is food that demands your full attention and rewards you with flavors so pure they\'re almost a form of worship.',
    address: 'Via Goffredo Mameli, 34, 91026 Mazara del Vallo TP',
    coordinates: { lat: 37.6532, lng: 12.5923 },
    priceRange: '$$$',
    timing: 'Dinner',
    tags: ['seafood', 'prawns', 'splurge', 'signature-dish'],
  },
  
  // Marzamemi
  {
    id: 'piazza-regina',
    name: 'Piazza Regina Margherita',
    city: 'marzamemi',
    type: 'attraction',
    description: 'Tiny main square at the heart of the fishing village',
    detailedDescription: 'The piazza is maybe forty feet across, but it contains multitudes. On summer evenings, the entire village seems to materialize here—children chasing soccer balls, old men arguing about football, teenagers flirting, tourists nursing Aperol spritzes. The Chiesa di San Francesco di Paola anchors one end, the old tonnara the other. String lights crisscross overhead. Someone\'s always playing guitar. This is Sicily in miniature: small, perfect, and somehow containing more life than spaces ten times its size.',
    address: 'Piazza Regina Margherita, 96018 Marzamemi SR',
    coordinates: { lat: 36.7305, lng: 15.1165 },
    priceRange: 'Free',
    timing: 'Evening',
    tags: ['piazza', 'village-life', 'atmospheric', 'evening'],
  },
  {
    id: 'osteria-da-gelsomino',
    name: 'Osteria Mediterranea Da Gelsomino',
    city: 'marzamemi',
    type: 'restaurant',
    description: 'Seafood osteria steps from the tonnara',
    detailedDescription: 'The tuna here was probably swimming this morning. That\'s how fishing villages work—the catch comes in at dawn and appears on your plate by lunch. Da Gelsomino does one thing spectacularly well: lets perfect ingredients speak for themselves. The tuna carpaccio is ruby red and dressed with nothing but good olive oil and lemon. The spaghetti ai ricci (sea urchin) is briny and sweet and just barely cooked. Sit outside on the tiny terrace, watch the sunset turn the tonnara pink, and thank whatever gods brought you to this tiny, perfect place.',
    address: 'Via Frassanito, 22, 96018 Marzamemi SR',
    coordinates: { lat: 36.7300, lng: 15.1172 },
    priceRange: '$$',
    timing: 'Lunch & Dinner',
    tags: ['seafood', 'tuna', 'fresh', 'terrace'],
  },
  
  // Giardini Naxos
  {
    id: 'nike-beach',
    name: 'Nike Beach',
    city: 'giardini-naxos',
    type: 'attraction',
    description: 'Sandy beach with views of Mount Etna and Taormina',
    detailedDescription: 'This is the beach where the Greeks first landed in 735 BC, making it the birthplace of Sicily as we know it. Today it\'s a long crescent of sand where locals actually swim, not just tourists. Mount Etna broods to the north, Taormina clings to its cliff above, and the water is that particular shade of blue that makes you question why you ever live anywhere with winter. Rent a lounger, swim out past the buoys, float on your back, and contemplate the fact that you\'re treading the same water as ancient Greek sailors. It\'s humbling and glorious in equal measure.',
    address: 'Via Naxos, 98035 Giardini Naxos ME',
    coordinates: { lat: 37.8238, lng: 15.2669 },
    priceRange: '$',
    timing: 'Morning & Afternoon',
    tags: ['beach', 'swimming', 'ancient-site', 'views'],
  },
  {
    id: 'o-palmentu',
    name: 'O\' Palmentu',
    city: 'giardini-naxos',
    type: 'restaurant',
    description: 'Beachfront restaurant serving fresh catch and Etna wines',
    detailedDescription: 'Your table is in the sand. Not near the sand—in it. The waves are close enough that you can hear them between courses. O\' Palmentu serves whatever came off the boats that morning: swordfish thick as steaks, squid so tender it yields to your fork, prawns grilled over lemon wood. The Etna bianco is cold and mineral and tastes vaguely of volcanic soil and summer thunderstorms. For dessert, they serve granita—not the slushy impostor, but proper Sicilian granita, crystalline and intense. This is the meal you\'ll remember when you\'re back home in February, staring at gray skies.',
    address: 'Via Tysandros, 16, 98035 Giardini Naxos ME',
    coordinates: { lat: 37.8251, lng: 15.2683 },
    priceRange: '$$',
    timing: 'Lunch & Dinner',
    tags: ['beachfront', 'seafood', 'etna-wine', 'memorable'],
  },
];
